name: oneapi-linux

env:
  CC: icx
  CXX: icpx
  FC: ifx
  CMAKE_BUILD_TYPE: Release
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.c"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/oneapi-linux.yml"


jobs:

  linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: cache install oneAPI
      id: cache-install
      uses: actions/cache@v4
      with:
        path: |
          /opt/intel/oneapi
        key: install-apt

    - name: non-cache install oneAPI
      if: steps.cache-install.outputs.cache-hit != 'true'
      timeout-minutes: 5
      run: |
        .github/workflows/oneapi_setup_apt_repo_linux.sh
        sudo apt install intel-oneapi-compiler-fortran

    - name: Setup Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV


    - run: cmake --workflow --preset default


    - name: exclude unused files from cache
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: .github/workflows/oneapi_cache_exclude_linux.sh
